// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0fzpNTd9iaW9_fCJhlcX4G5y9_raOMpw',
    appId: '1:354094372796:web:b24b4c6580a30a7e013db9',
    messagingSenderId: '354094372796',
    projectId: 'local-a216d',
    authDomain: 'local-a216d.firebaseapp.com',
    storageBucket: 'local-a216d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmNF9A-lqhb4XvJVYDLGOXANHAXY36Ioc',
    appId: '1:354094372796:android:56685190208ee47d013db9',
    messagingSenderId: '354094372796',
    projectId: 'local-a216d',
    storageBucket: 'local-a216d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASUfUwO6-63cUnczIX6IXTSqR84-HNsZs',
    appId: '1:354094372796:ios:da165c13f3df0dc6013db9',
    messagingSenderId: '354094372796',
    projectId: 'local-a216d',
    storageBucket: 'local-a216d.firebasestorage.app',
    iosBundleId: 'com.example.local',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASUfUwO6-63cUnczIX6IXTSqR84-HNsZs',
    appId: '1:354094372796:ios:da165c13f3df0dc6013db9',
    messagingSenderId: '354094372796',
    projectId: 'local-a216d',
    storageBucket: 'local-a216d.firebasestorage.app',
    iosBundleId: 'com.example.local',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0fzpNTd9iaW9_fCJhlcX4G5y9_raOMpw',
    appId: '1:354094372796:web:dcc29dde8637006d013db9',
    messagingSenderId: '354094372796',
    projectId: 'local-a216d',
    authDomain: 'local-a216d.firebaseapp.com',
    storageBucket: 'local-a216d.firebasestorage.app',
  );
}
